[build-system]
requires = ["setuptools ~= 58.0"]

[project]
dependencies = []
description = 'Terraform CI Action'
name = 'terraform_ci'
version = "0.3.1"

[tool.setuptools.packages.find]
include = ["terraform_ci*"]
namespaces = false
